# Generated by Django 3.2.7 on 2021-10-30 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recsys', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='session_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='userproductview',
            name='session_id',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='productrating',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='userproductview',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
