# Generated by Django 3.2.7 on 2021-11-04 04:24

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20211104_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='properties',
            field=django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], size=None),
        ),
    ]
